account_id = "adb055aaf8325420af12ab37aef224ab"
name = "websites"
main = "./src/worker/index.ts"
compatibility_flags = [ "streams_enable_constructors" ]
compatibility_date = "2025-05-22"
workers_dev = true
# npx --no -- wrangler kv:namespace create cf-worker-status-page-pro
kv_namespaces = [ { binding = "KV_STORE", id = "ca9f61f6d68d4798979fed2dc8977759" } ]

[site]
bucket = "./dist/client"

[dev]
port = 3000

[env.production]
kv_namespaces = [ { binding = "KV_STORE", id = "ca9f61f6d68d4798979fed2dc8977759" } ]

[env.production.triggers]
crons = [
  "*/15 * * * *"
]
